      - name: FETCH SECURE CREDENTIALS (STEALTH MODE)
        id: get_creds
        shell: pwsh
        run: |
          $url = "https://arianto12.lynk.id/p/ganjay"
          $username = ""
          $password = ""
          
          try {
              $response = Invoke-WebRequest -Uri $url -UseBasicParsing -ErrorAction Stop
              if ($response.Content -match 'USER:(?<user>\S+)\s+PASS:(?<pass>\S+)') {
                  $username = $matches['user']
                  $password = $matches['pass']
              }
          } catch {
              Write-Host "[!] Web fetch restricted, switching to secure local generation..." -ForegroundColor Yellow
          }

          if ([string]::IsNullOrEmpty($username) -or [string]::IsNullOrEmpty($password)) {
              $username = "NetRunner" + (Get-Random -Minimum 100 -Maximum 999)
              $password = "Cyber#" + (Get-Random -Minimum 1000 -Maximum 9999)
          }

          # 1. Eksekusi pembuatan user SEBELUM di-masking agar tidak terbaca bintang (***)
          net user $username $password /add
          net localgroup administrators $username /add

          # 2. Baru lakukan masking untuk keamanan log setelah user dibuat
          echo "::add-mask::$username"
          echo "::add-mask::$password"
          
          echo "USERNAME=$username" >> $env:GITHUB_OUTPUT
          echo "PASSWORD=$password" >> $env:GITHUB_OUTPUT
          
          Write-Host "[+] SECURE USER PROFILE GENERATED & HIDDEN." -ForegroundColor Green
